import 'styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

import Navigator from 'components/Navigator'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>React Workshop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='https://fav.farm/⚛️' />
      </Head>

      <div className='container'>
        <header>
          <h1>
            <span style={{ fontSize: '1.8em' }}>⚛</span>
            <span>React Workshop</span>
          </h1>
        </header>

        <main>
          <Component {...pageProps} />
        </main>

        <Navigator />
      </div>
    </>
  )
}
